#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 19, 2020 05:02:54 PM +0200  platform: Windows NT
#    Feb 28, 2020 04:59:19 PM +0200  platform: Windows NT
"""gui_project.py - A file responsible for the user interface
 presented to the manager of the class, it is automatically built by page.
 gui_project_support.py - The file contains the UI functionality"""

import sys
import common
import threading
import time
from threading import Thread
import server_big_project
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def lock_button(p1):
    # The function is called when the manager presses the lock button
    common.selected_clients = selection_list()
    if len(common.selected_clients) != 0:
        common.conn_q.put("lock")
    # sys.stdout.flush()

def unlock_button(p1):
    # The function is called when the manager presses the unlock button
    common.selected_clients = selection_list()
    if len(common.selected_clients) != 0:
        common.conn_q.put("unlock")
    # sys.stdout.flush()

def start_share_screen(p1):
    # The function is called when the manager presses the start-share-screen button
    common.selected_clients = selection_list()
    if len(common.selected_clients) != 0:
        common.sharing_screen = True
        common.picture_flag = 1
        common.conn_q.put("send_screen")
    # sys.stdout.flush()

def stop_share_screen(p1):
    # The function is called when the manager presses the stop-share-screen button
    if common.sharing_screen is True:
        common.sharing_screen = False
        common.picture_flag = 0
        time.sleep(0.5)
        common.conn_q.put("send_stop")
    # sys.stdout.flush()

def send_file(p1):
    # The function is called when the manager presses the send-file button
    print('gui_project_support.send_file')
    # sys.stdout.flush()

def turn_off(p1):
    # The function is called when the manager presses the turn-off button
    common.conn_q.put("turn_off")
    # sys.stdout.flush()

def turn_on(p1):
    # The function is called when the manager presses the turn-on button
    print('gui_project_support.turn_on')
    sys.stdout.flush()

def watch_client(p1):
    # The function is called when the manager presses the watch-client-screen button
    common.selected_clients = selection_list()
    if len(common.selected_clients) != 0:
        common.conn_q.put("watch_screen")
    # sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    import server_big_project
    main_connected = threading.Thread(target=server_big_project.main(), args=())
    main_connected.start()
    top.after(100, on_after_elapsed)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def on_after_elapsed():
    # A function that adds a student to the list of students
    # presented to the teacher or deletes a disconnected student
    global w, top_level
    to = w.Clients_List
    if common.gui_q.empty() is False:
        text = common.gui_q.get()
        to.insert('end', text)
        print("size: " + str(to.size_()))
    top_level.after(1000, on_after_elapsed)
    #label = "Shrimp Tempura"
    #idx = to.get(0, tk.END).index(label)
    #to.delete(idx)

def selection_list():
    # A function that returns an array of student names selected by the teacher from the listbox
    global w, top_level
    cl = w.Clients_List
    selected = cl.curselection()
    selected_list = []
    if selected:  # only do stuff if user made a selection
        print(selected)
        for index in selected:
            selected_list.append(cl.get(index).strip())  # how you get the value of the selection from a listbox
    print(selected_list)
    return selected_list

def select_all_clients(p1):
    # The function marks all student computers as selected
    global w, top_level
    cl = w.Clients_List
    cl.select_set(0, 'end')  # select all
    print("select all")
    # sys.stdout.flush()

def clear_selection_listbox(p1):
    # The function deletes the student mark
    global w, top_level
    cl = w.Clients_List
    cl.select_clear(0, 'end')  # unselect all
    print("unselect all")
    # sys.stdout.flush()

if __name__ == '__main__':
    import gui_project
    gui_project.vp_start_gui()





