#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Feb 28, 2020 05:02:45 PM +0200  platform: Windows NT
set vTcl(timestamp) ""


set image_list { \
    lock1_jpg ../Users/yuval/Desktop/BigProject/images/Lock1.jpg \
    send_file_png ../Users/yuval/Desktop/BigProject/images/send_file.png \
    start_transfer_png ../BigProject/images/start_transfer.png \
    stop_transfer_png ../Users/yuval/Desktop/BigProject/images/stop_transfer.png \
    turn_off1_png ../BigProject/images/turn_off1.png \
    turn_on1_png ../Users/yuval/Desktop/BigProject/images/turn_on1.png \
    unlock1_jpg ../Users/yuval/Desktop/BigProject/images/Unlock1.jpg \
    watch_screen_png ../Users/yuval/Desktop/BigProject/images/watch_screen.png \
}
   vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #70b8b8 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 973x754+447+116
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Control Net"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief ridge -background $vTcl(actual_gui_bg) \
        -height 735 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 955 
    vTcl:DefineAlias "$top.fra43" "Frame_Features" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    button $site_3_0.but44 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image lock1_jpg -pady 0 
    vTcl:DefineAlias "$site_3_0.but44" "Lock_Button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but44 <Button-1> {
        lambda e: lock_button(e)
    }
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image unlock1_jpg -pady 0 
    vTcl:DefineAlias "$site_3_0.but45" "Unlock_button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but45 <Button-1> {
        lambda e: unlock_button(e)
    }
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image start_transfer_png -pady 0 
    vTcl:DefineAlias "$site_3_0.but46" "Start_Sharing" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but46 <Button-1> {
        lambda e: start_share_screen(e)
    }
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image stop_transfer_png -pady 0 
    vTcl:DefineAlias "$site_3_0.but47" "Stop_Sharing" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but47 <Button-1> {
        lambda e: stop_share_screen(e)
    }
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image turn_on1_png -pady 0 
    vTcl:DefineAlias "$site_3_0.but48" "TurnOn_Button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but48 <Button-1> {
        lambda e: turn_on(e)
    }
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image turn_off1_png -pady 0 
    vTcl:DefineAlias "$site_3_0.but49" "TurnOff_Button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but49 <Button-1> {
        lambda e: turn_off(e)
    }
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image send_file_png -pady 0 
    vTcl:DefineAlias "$site_3_0.but50" "SendFile_Button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but50 <Button-1> {
        lambda e: send_file(e)
    }
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image watch_screen_png -pady 0 
    vTcl:DefineAlias "$site_3_0.but51" "WatchScreen_Button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but51 <Button-1> {
        lambda e: watch_client(e)
    }
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr52 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_3_0.scr52" "Clients_List" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr52.01 configure -background #ffffbd \
        -disabledforeground #a3a3a3 \
        -font font10 \
        -foreground #0080ff \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #ffff0b \
        -selectforeground #0000a0 \
        -selectmode multiple \
        -width 10
    button $site_3_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #83b4fc -cursor hand2 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight bold} -foreground #000080 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Select All Clients} 
    vTcl:DefineAlias "$site_3_0.but53" "Select_All" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but53 <Button-1> {
        lambda e: select_all_clients(e)
    }
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #83b4fc -cursor hand2 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight bold} -foreground #000080 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Clear Selection} 
    vTcl:DefineAlias "$site_3_0.but54" "Clear_Selection" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but54 <Button-1> {
        lambda e: clear_selection_listbox(e)
    }
    place $site_3_0.but44 \
        -in $site_3_0 -x 10 -y 10 -width 160 -relwidth 0 -height 160 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 10 -y 190 -width 160 -relwidth 0 -height 160 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 190 -y 10 -width 160 -relwidth 0 -height 160 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 190 -y 190 -width 160 -relwidth 0 -height 160 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 370 -y 10 -width 160 -relwidth 0 -height 160 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 370 -y 190 -width 160 -relwidth 0 -height 160 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 550 -y 10 -width 160 -relwidth 0 -height 160 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 550 -y 190 -width 160 -relwidth 0 -height 160 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr52 \
        -in $site_3_0 -x 10 -y 360 -width 465 -relwidth 0 -height 367 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 500 -y 390 -width 196 -relwidth 0 -height 53 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 500 -y 470 -width 196 -relwidth 0 -height 53 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 10 -y 10 -width 955 -relwidth 0 -height 735 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

