#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#    May 09, 2020 02:40:05 AM +0300  platform: Windows NT
#    May 11, 2020 01:57:32 PM +0300  platform: Windows NT
#    May 11, 2020 02:20:45 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from finals import Finals as final
import time

def exb():
    pass

def init(top, gui, *args, **kwargs):
    global w, top_level, root, entry_name, error, start_btn
    w = gui
    top_level = top
    root = top
    top_level.protocol("WM_DELETE_WINDOW", exb)  # hide close button
    entry_name = w.student_name
    error = w.error_message
    start_btn = w.start_button

def clear_entry(o):
    o.delete(0, 'end')

def on_pressed(p1):
    error['text'] = ""
    st_name = str(entry_name.get())
    clear_entry(entry_name)
    if len(st_name) > 15 or len(st_name) == 0 or " " in st_name:
        error['text'] = "Invalid name. Enter your name between 1-15 characters and no spaces."
    else:
        final.conn_q.put("new client" + st_name)
        time.sleep(1)
        if final.error_message != "":
            error['text'] = final.error_message
        else:
            destroy_window()
    # sys.stdout.flush()

def over_off(p1):
    start_btn["background"] = "#cecece"
    # sys.stdout.flush()

def over_on(p1):
    start_btn["background"] = "#a2a2a2"
    # sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui_client
    gui_client.vp_start_gui()
